# Generated by Django 3.1.2 on 2020-10-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0003_produit_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='employe',
        ),
    ]
