# Generated by Django 3.1.2 on 2020-11-06 01:32

from django.db import migrations, models
from gestion_fournisseur.models import Fournisseur
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fournisseur', '0003_auto_20201105_1322'),
        ('gestion_produit', '0004_remove_produit_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_fournisseur.fournisseur'),
            preserve_default=False,
        ),
    ]
