# Generated by Django 3.1.2 on 2020-11-06 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fournisseur', '0003_auto_20201105_1322'),
        ('gestion_produit', '0005_produit_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion_fournisseur.fournisseur'),
        ),
    ]
