# Generated by Django 3.1.2 on 2020-11-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0006_auto_20201106_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image1',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='produit',
            name='image2',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
