# Generated by Django 3.1.2 on 2020-11-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0007_auto_20201109_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
