# Generated by Django 3.1.2 on 2020-11-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0008_auto_20201109_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssaiImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
