# Generated by Django 3.1.2 on 2020-10-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_auto_20201022_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'm'), ('Feminin', 'f')], default='Masculin', max_length=10),
        ),
    ]
