# Generated by Django 3.1.2 on 2020-10-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_employe_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('g_p', 'Gestionnaire de produits'), ('g_c', 'Gestionnaire de commande')], default='g_p', max_length=10),
        ),
    ]
