# Generated by Django 3.1.2 on 2020-10-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_employe_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='login',
            field=models.CharField(default='', max_length=100),
        ),
    ]
