# Generated by Django 3.1.2 on 2020-11-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0005_employe_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('g_p', 'Gestionnaire de produits'), ('g_c', 'Gestionnaire de commande'), ('g_f', 'Gestionnaire de fournisseur')], default='g_p', max_length=10),
        ),
    ]
