# Generated by Django 3.1.2 on 2020-11-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0008_message_destinataire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
    ]
