# Generated by Django 3.1.2 on 2020-11-11 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0009_auto_20201110_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2020, 11, 11)),
        ),
        migrations.AlterField(
            model_name='message',
            name='lire',
            field=models.IntegerField(default=0),
        ),
    ]
