# Generated by Django 3.1.2 on 2020-11-13 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0010_auto_20201111_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2020, 11, 13)),
        ),
    ]
