# Generated by Django 3.1.2 on 2020-11-17 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0012_auto_20201114_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2020, 11, 17)),
        ),
    ]
