# Generated by Django 3.1.2 on 2020-11-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='etat',
            field=models.IntegerField(default=0),
        ),
    ]
