# Generated by Django 3.1.2 on 2020-11-05 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fournisseur', '0002_auto_20201105_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailDevis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_devis', models.DateField()),
                ('nbre_produit', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='AjoutProd',
        ),
        migrations.AddField(
            model_name='detaildevis',
            name='devis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_fournisseur.devis'),
        ),
        migrations.AddField(
            model_name='detaildevis',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_fournisseur.fournisseur'),
        ),
    ]
