# Generated by Django 3.1.2 on 2020-11-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fournisseur', '0003_auto_20201105_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='etat',
            field=models.IntegerField(default=0),
        ),
    ]
