# Generated by Django 3.1.2 on 2020-11-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fournisseur', '0004_devis_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='ajouter',
            field=models.IntegerField(default=0),
        ),
    ]
