# Generated by Django 3.1.2 on 2020-11-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fournisseur', '0005_devis_ajouter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='ajouter',
        ),
        migrations.AddField(
            model_name='detaildevis',
            name='ajouter',
            field=models.IntegerField(default=0),
        ),
    ]
