# Generated by Django 3.1.2 on 2020-11-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fournisseur', '0006_auto_20201107_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detaildevis',
            name='fournisseur',
        ),
        migrations.AddField(
            model_name='devis',
            name='fournisseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_fournisseur.fournisseur'),
            preserve_default=False,
        ),
    ]
